### ISSUE TITLE
"if" directive not allowed wp_supercache.conf

### ISSUE THREAD

**Issue by Onegaishimasu** [perusio/wordpress-nginx#3]
I'm trying to setup a Wordpress site, running nginx 1.2.0 with php 5.3.13, php-fpm and WP Super Cache. My nginx config files are stored in /usr/local, with my vhost.conf and wp_supercache.conf stored in /conf/conf.d (rather than the default directory, sites-available, listed in your setup). I've changed the "include" paths at the end of my main config file to reflect this (include conf.d/*.conf;).

After doing all of this, restarting nginx, I get the following error:

"if" directive is not allowed here in /usr/local/nginx/conf/conf.d/wp_supercache.conf

When I look at the wp_supercache.conf, I see it does use the "if" directive a number of times. I understand from reading the nginx.org wiki ('"if" is evil') that I should be using the "try_files" directive instead. Unfortunately, my grasp of nginx isn't strong enough yet to rewrite wp_supercache.conf in the way they're suggesting.

**Comment by perusio** [comment]
If is not evil of used for returns only. Which is the case. That wiki page is related to the abuses made by using if as if were a real if, and not a _location in desguise_. Which it really is. The thing to remember is that it runs at the rewrite phase. I haven't yet found the time yet to replace all those tests by  `map` directives plus a single `if.

Probably you're including `wp_supercache.conf` at the wrong, level. Are you sure you're including it inside the `/` location?

https://github.com/perusio/wordpress-nginx/blob/master/sites-available/example.com.conf#L69
